project:
  type: book
  output-dir: docs

book:
  title: "Foundations of Genomics and Proteomics"
  subtitle: "Life's Source Code – From DNA to Data"
  author:
    name: "Pawan Rama Mali"
    email: "prm@outlook.in"
    orcid: "0000-0001-7864-5819"
  date: today

  chapters:
    - index.qmd

    - part: "Part I – Foundations of Molecular Biology"
      chapters:
        - ch01-introduction.qmd
        - ch02-basics.qmd
        - ch03-central-dogma.qmd
        - ch03a-cell-division.qmd

    - part: "Part II – Historical Perspectives"
      chapters:
        - ch04-classical-genetics.qmd
        - ch05-dna-discovery.qmd
        - ch06-molecular-era.qmd

    - part: "Part III – Genomes"
      chapters:
        - ch07-genome.qmd
        - ch08-prokaryotic-eukaryotic.qmd
        - ch09-packaging.qmd
        - ch10-c-value-paradox.qmd
        - ch11-mitochondria.qmd
        - ch11a-comparative-genomics.qmd
        - ch11b-genetic-variation.qmd
        - ch11c-recombination-mapping.qmd
        - ch11d-model-organisms.qmd
        - ch11e-population-genetics.qmd
        - ch11f-quantitative-genetics.qmd
        - ch11g-molecular-evolution.qmd

    - part: "Part IV – Beyond the Genome"
      chapters:
        - ch12-transcriptomics.qmd
        - ch12a-gene-regulation.qmd
        - ch13-proteomics.qmd
        - ch14-epigenetics.qmd
        - ch14a-metabolomics.qmd
        - ch14b-noncoding-rna.qmd
        - ch14b1-mirna-mechanisms.qmd
        - ch14c-protein-structure.qmd

    - part: "Part V – Experimental Tools and Applications"
      chapters:
        - ch15-sequencing.qmd
        - ch16-experimental-methods.qmd
        - ch16a-functional-genomics.qmd
        - ch17-applications.qmd
        - ch17a-bioinformatics.qmd
        - ch17b-metagenomics.qmd
        - ch17c-ngs-analysis.qmd
        - ch17d-cancer-genomics.qmd
        - ch17e-pharmacogenomics.qmd
        - ch17f-systems-biology.qmd

    - part: "Part VI – Reflection and Future Directions"
      chapters:
        - ch18-discussion.qmd
        - ch19-future-omics.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: false
    link-external-icon: true
    link-external-newwindow: true
